### ISSUE TITLE
If there contains a map in odatalist, the EasyConverts class throws exception.

### ISSUE THREAD

**Issue by gewanbo** [gewanbo/easyapi#2]
If there contains a map in odatalist, the EasyConverts class throws exception.

Exception message below:

```
at com.wanbo.easyapi.server.lib.EasyConverts$$anonfun$list2json$1$$anonfun$apply$1.apply(EasyConverts.scala:41) ~[easyapi.server-1.0.17-SNAPSHOT.jar:na]
at com.wanbo.easyapi.server.lib.EasyConverts$$anonfun$list2json$1$$anonfun$apply$1.apply(EasyConverts.scala:40) ~[easyapi.server-1.0.17-SNAPSHOT.jar:na]
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library-2.10.4.jar:na]
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244) ~[scala-library-2.10.4.jar:na]
at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:224) ~[scala-library-2.10.4.jar:na]
at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:403) ~[scala-library-2.10.4.jar:na]
at scala.collection.TraversableLike$class.map(TraversableLike.scala:244) ~[scala-library-2.10.4.jar:na]
at scala.collection.AbstractTraversable.map(Traversable.scala:105) ~[scala-library-2.10.4.jar:na]
at com.wanbo.easyapi.server.lib.EasyConverts$$anonfun$list2json$1.apply(EasyConverts.scala:40) ~[easyapi.server-1.0.17-SNAPSHOT.jar:na]
at com.wanbo.easyapi.server.lib.EasyConverts$$anonfun$list2json$1.apply(EasyConverts.scala:36) ~[easyapi.server-1.0.17-SNAPSHOT.jar:na]
at scala.collection.immutable.List.foreach(List.scala:318) ~[scala-library-2.10.4.jar:na]
at com.wanbo.easyapi.server.lib.EasyConverts$.list2json(EasyConverts.scala:36) ~[easyapi.server-1.0.17-SNAPSHOT.jar:na]
at com.wanbo.easyapi.server.lib.SeederManager.farming(SeederManager.scala:111) ~[easyapi.server-1.0.17-SNAPSHOT.jar:na]
at com.wanbo.easyapi.server.actors.Worker.process(Worker.scala:57) ~[easyapi.server-1.0.17-SNAPSHOT.jar:na]
at com.wanbo.easyapi.server.actors.Worker$$anonfun$receive$1.applyOrElse(Worker.scala:33) ~[easyapi.server-1.0.17-SNAPSHOT.jar:na]
at akka.actor.Actor$class.aroundReceive(Actor.scala:465) ~[akka-actor_2.10-2.3.9.jar:na]
at com.wanbo.easyapi.server.actors.Worker.aroundReceive(Worker.scala:15) ~[easyapi.server-1.0.17-SNAPSHOT.jar:na]
at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) ~[akka-actor_2.10-2.3.9.jar:na]
at akka.actor.ActorCell.invoke(ActorCell.scala:487) ~[akka-actor_2.10-2.3.9.jar:na]
at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) ~[akka-actor_2.10-2.3.9.jar:na]
at akka.dispatch.Mailbox.run(Mailbox.scala:221) ~[akka-actor_2.10-2.3.9.jar:na]
at akka.dispatch.Mailbox.exec(Mailbox.scala:231) ~[akka-actor_2.10-2.3.9.jar:na]
at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) ~[scala-library-2.10.4.jar:na]
at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) ~[scala-library-2.10.4.jar:na]
at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) ~[scala-library-2.10.4.jar:na]
```

**Comment by gewanbo** [comment]
Fixed.
